# Generated by Django 3.0.2 on 2020-02-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameId', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImdbId', models.IntegerField(unique=True)),
                ('Title', models.CharField(max_length=200)),
                ('Imdb_rating', models.FloatField(null=True)),
                ('Image_link', models.CharField(max_length=1000, null=True)),
                ('Year', models.CharField(max_length=4, null=True)),
                ('Rating', models.FloatField(null=True)),
                ('Num_ratings', models.IntegerField(null=True)),
                ('Directors', models.ManyToManyField(related_name='Directors', to='Movies.People')),
                ('Genres', models.ManyToManyField(to='Movies.Genre')),
                ('Writers', models.ManyToManyField(related_name='Writers', to='Movies.People')),
            ],
        ),
    ]
