# Generated by Django 3.0.2 on 2020-02-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='RunTime',
            field=models.IntegerField(null=True),
        ),
    ]
