# Generated by Django 2.2.5 on 2020-02-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ImdbId',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Num_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='RunTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
