# Generated by Django 2.2.5 on 2020-02-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_auto_20200203_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Num_ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
