# Generated by Django 2.2.5 on 2020-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_newrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='NameId',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
